<?php get_header();?>
<main>
<section class="lmh-hero"><div class="lmh-shell"><div class="lmh-kicker">WELCOME TO LE MANAGER HUB</div><h1>THE GLOBAL MUSIC INDUSTRY HUB</h1><p>Connect artists, managers, producers, promoters, labels, media, brands, fans, venues and entertainment professionals in one powerful ecosystem.</p><p><a class="lmh-btn" href="<?php echo esc_url(wp_registration_url());?>">JOIN LE MANAGER HUB</a> <a class="lmh-btn dark" href="#discover">DISCOVER THE NETWORK</a></p></div></section>
<section id="discover" class="lmh-section"><div class="lmh-shell"><div class="lmh-kicker">Discover</div><h2 class="lmh-title">One Industry. One Global Ecosystem.</h2><div class="lmh-grid"><?php foreach(['Artists','Industry Professionals','Companies & Brands','Global Directory'] as $x):?><div class="lmh-card"><h3><?php echo esc_html($x);?></h3><p>Search, connect, discover and build professional relationships across the global entertainment industry.</p></div><?php endforeach;?></div></div></section>
<section id="professionals" class="lmh-section dark"><div class="lmh-shell"><div class="lmh-kicker">Professional Network</div><h2 class="lmh-title">Built for the People Behind the Industry</h2><div class="lmh-grid"><?php foreach(['Artists & Managers','Producers & Songwriters','Promoters & Booking Agents','Labels & Distributors','Studios & Engineers','Media & DJs','Lawyers & Publicists','Venues & Sponsors'] as $x):?><div class="lmh-card"><h3><?php echo esc_html($x);?></h3><p>Create a profile, showcase work and connect with opportunities.</p></div><?php endforeach;?></div></div></section>
<section id="opportunities" class="lmh-section"><div class="lmh-shell"><div class="lmh-kicker">Opportunities</div><h2 class="lmh-title">Turn Connections Into Opportunities</h2><div class="lmh-grid"><?php $q=new WP_Query(['post_type'=>'lmh_opportunity','posts_per_page'=>4]);if($q->have_posts()):while($q->have_posts()):$q->the_post();?><article class="lmh-card"><h3><?php the_title();?></h3><?php the_excerpt();?></article><?php endwhile;wp_reset_postdata();else:foreach(['Artist Bookings','Festival & Event Calls','Music Submissions','Brand Partnerships'] as $x):?><div class="lmh-card"><h3><?php echo esc_html($x);?></h3><p>New opportunities will appear here from the Le Manager Hub backend.</p></div><?php endforeach;endif;?></div></div></section>
<section id="events" class="lmh-section dark"><div class="lmh-shell"><div class="lmh-kicker">Events</div><h2 class="lmh-title">Concerts. Festivals. Showcases. Experiences.</h2><p>Discover events and connect artists, promoters, venues, brands and fans.</p></div></section>
<section id="media" class="lmh-section"><div class="lmh-shell"><div class="lmh-kicker">Media Network</div><h2 class="lmh-title">Le Manager TV • Radio • Podcast</h2><div class="lmh-grid"><?php foreach(['Le Manager TV','Le Manager Radio','Le Manager Podcast','Industry News'] as $x):?><div class="lmh-card"><h3><?php echo esc_html($x);?></h3><p>Original media, interviews, premieres, performances and industry conversations.</p></div><?php endforeach;?></div></div></section>
<section id="fans" class="lmh-section dark"><div class="lmh-shell"><div class="lmh-kicker">Le Manager Fans</div><h2 class="lmh-title">JOIN THE LE MANAGER MOVEMENT</h2><p>Follow artists, discover events, unlock experiences and become part of the community.</p><div class="lmh-grid"><?php foreach(['LM Fan','LM Insider','LM Ambassador','LM VIP'] as $x):?><div class="lmh-card"><h3><?php echo esc_html($x);?></h3><p>Grow through participation, community and Le Manager experiences.</p></div><?php endforeach;?></div></div></section>
<section id="bookings" class="lmh-section"><div class="lmh-shell"><div class="lmh-kicker">Bookings</div><h2 class="lmh-title">Discover → Connect → Book</h2><p>Our backend supports private booking requests. Quotes, contracts and payments are planned for the next phase.</p><a class="lmh-btn" href="<?php echo esc_url(wp_login_url());?>">ACCESS YOUR ACCOUNT</a></div></section>
</main><?php get_footer();?>