<?php get_header();?><main id="main" class="lmh-section"><div class="lmh-shell lmh-reading"><?php while(have_posts()):the_post();$type=get_post_type();$id=get_the_ID();$profile=in_array($type,['lmh_artist','lmh_professional','lmh_company'],true);$verified=get_post_meta($id,'_lmh_verified_level',true);$cover=get_post_meta($id,'_lmh_cover_image_url',true);?>
<article class="<?php echo $profile?'lmh-public-profile':'';?>">
<?php if($profile&&$cover):?><div class="lmh-profile-cover" style="background-image:url('<?php echo esc_url($cover);?>')"></div><?php endif;?>
<div class="lmh-kicker"><?php echo esc_html(get_post_type_object($type)->labels->singular_name);?></div>
<h1 class="lmh-title"><?php the_title();?> <?php if($profile&&in_array($verified,['verified','featured'],true)):?><span class="lmh-verified" title="Verified by Le Manager">✓ VERIFIED</span><?php endif;?></h1>
<?php if(has_post_thumbnail()):?><div class="lmh-profile-photo"><?php the_post_thumbnail('large');?></div><?php endif;?>
<?php if($profile):?>
<div class="lmh-profile-actions">
<?php $booking=get_post_meta($id,'_lmh_booking_email',true);if($booking):?><a class="lmh-btn" href="#booking">BOOK NOW</a><?php endif;?>
<?php $portfolio=get_post_meta($id,'_lmh_portfolio_url',true);if($portfolio):?><a class="lmh-btn" href="<?php echo esc_url($portfolio);?>" target="_blank" rel="noopener">VIEW PORTFOLIO</a><?php endif;?>
</div>
<?php endif;?>
<div class="lmh-profile-bio"><?php the_content();?></div>
<?php if($profile):?>
<div class="lmh-grid lmh-profile-highlights">
<?php foreach(['city'=>'Location','services'=>'Services','languages'=>'Languages','availability'=>'Availability','achievements'=>'Achievements'] as $key=>$label){$v=get_post_meta($id,'_lmh_'.$key,true);if($v)echo '<article class="lmh-card"><h3>'.esc_html($label).'</h3><p>'.nl2br(esc_html($v)).'</p></article>';}?>
</div>
<?php $socials=['website'=>'Website','instagram'=>'Instagram','tiktok'=>'TikTok','facebook'=>'Facebook','x'=>'X / Twitter','spotify'=>'Spotify','apple_music'=>'Apple Music','youtube'=>'YouTube'];$links=[];foreach($socials as $key=>$label){$v=get_post_meta($id,'_lmh_'.$key,true);if($v)$links[$label]=$v;}if($links):?><section class="lmh-profile-social"><h2>Connect</h2><div class="lmh-profile-actions"><?php foreach($links as $label=>$url):?><a class="lmh-text-link" href="<?php echo esc_url($url);?>" target="_blank" rel="noopener"><?php echo esc_html($label);?> →</a><?php endforeach;?></div></section><?php endif;?>
<?php else:?><dl class="lmh-details"><?php foreach(get_registered_meta_keys('post',$type) as $key=>$schema){$value=get_post_meta($id,$key,true);if(!$value||strpos($key,'_lmh_')!==0||in_array($key,['_lmh_video_url','_lmh_audio_url','_lmh_stream_url'],true))continue;$label=ucwords(str_replace('_',' ',substr($key,5)));echo '<dt>'.esc_html($label).'</dt><dd>';if(preg_match('#^https?://#i',$value))echo '<a href="'.esc_url($value).'" rel="noopener">'.esc_html($label).' →</a>';else echo esc_html($value);echo '</dd>';}?></dl><?php endif;?>
<?php foreach(get_object_taxonomies($type,'objects') as $tax){echo get_the_term_list($id,$tax->name,'<div class="lmh-profile-tax"><strong>'.esc_html($tax->label).':</strong> ',', ','</div>')?:'';}?>
<?php foreach(['_lmh_video_url'=>'video','_lmh_audio_url'=>'audio','_lmh_stream_url'=>'audio'] as $key=>$format){$url=get_post_meta($id,$key,true);if(!$url)continue;$url=esc_url($url);if(!$url)continue;if($format==='video'&&preg_match('/\.(mp4|webm)(\?.*)?$/i',$url))echo wp_video_shortcode(['src'=>$url]);elseif($format==='audio')echo wp_audio_shortcode(['src'=>$url]);else{$embed=wp_oembed_get($url);echo $embed?:'<p><a class="lmh-btn" href="'.$url.'" rel="noopener">WATCH PROGRAM →</a></p>';}}
if($type==='lmh_artist'):$following=array_map('intval',(array)get_user_meta(get_current_user_id(),'lmh_following',true));?><button class="lmh-btn" data-follow="<?php echo esc_attr($id);?>" aria-pressed="<?php echo in_array($id,$following,true)?'true':'false';?>"><?php echo in_array($id,$following,true)?'UNFOLLOW ARTIST':'FOLLOW ARTIST';?></button><p id="follow-status" role="status"></p><?php endif;?>
<?php if($profile):?><section id="booking" class="lmh-squad"><h2>Request a Booking</h2><p>Send a professional booking request through Le Manager.</p><?php if(!is_user_logged_in()):?><a class="lmh-btn" href="<?php echo esc_url(wp_login_url(get_permalink()));?>">SIGN IN TO REQUEST A BOOKING</a><?php else:?><form class="lmh-form" data-api="bookings"><input type="hidden" name="talent_id" value="<?php echo esc_attr($id);?>"><label>Event date<input type="date" name="event_date" required min="<?php echo esc_attr(current_time('Y-m-d'));?>"></label><label>Budget & currency<input name="budget" required maxlength="100" placeholder="e.g. USD 2,000"></label><label>Tell us about your event<textarea name="message" required maxlength="5000" rows="5"></textarea></label><button class="lmh-btn">SEND BOOKING REQUEST</button><p role="status" aria-live="polite"></p></form><?php endif;?></section><?php endif;?>
</article><?php endwhile;?></div></main><?php get_footer();?>